name: air_quality_prediction
services:
  streamlit:
    build: docker/streamlit
    image: shandytp/ml_process_streamlit_demo
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8501:8501
    volumes:
      - ./:/home/
  api:
    build: docker/api
    image: shandytp/ml_process_api_demo
    container_name: api_backend
    ports:
      - 8080:8080
    volumes:
      - ./:/home/
    environment:
      - PYTHONPATH=/home
